import type { Metadata } from "next";
// import "./globals.css";
import { Roboto } from 'next/font/google'
import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";
import { Container, Header } from "@/styles/pages/layout";
import logoImg from '@/assets/ignite_shop_logo.svg'
import Image from "next/image";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  globalStyles();

  return (
    <html lang="pt-br">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body
        className={roboto.className}
      >
        <Container>
          <Header>
            <Image src={logoImg} alt="" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
